#!/bin/bash
PROJ_NAME=Braindump

sudo yum install docker -y
sudo service docker start
sudo usermod -a -G docker $USER

sudo yum install nginx -y
sudo rm /etc/nginx/nginx.conf
sudo ln -s "/home/ec2-user/$PROJ_NAME/nginx/nginx.conf" /etc/nginx/nginx.conf
sudu systemctl start nginx
sudo systemctl enable nginx
