#!/bin/bash
PROJ_NAME=Braindump
DOMAIN=lanceberge.dev

yum install docker -y
service docker start
usermod -a -G docker ec2-user

yum install nginx -y

cat <<'EOF' > /etc/nginx/nginx.conf
worker_processes 1;
events {
    worker_connections 1024;
}
http {
    include mime.types;
    include /etc/nginx/sites-enabled/*;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
}
EOF

echo "set -o vi" >> ~/.bashrc

mkdir -p /etc/nginx/sites-enabled
ln -s "/home/ec2-user/$PROJ_NAME/nginx/nginx.conf" /etc/nginx/sites-enabled/"$PROJ_NAME"
systemctl start nginx
systemctl enable nginx

yum install certbot python3-certbot-nginx -y
certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN"
